### ISSUE TITLE
Notification misdirect

### ISSUE THREAD

**Issue by hansfordj** [tari-project/wallet-android#390] opened 2020-05-24 19:58 UTC
Opening a notification of a new transaction directs to an old transaction with past message.
Showing "Waiting for sender to complete transaction" for the previous transaction that is confirmed.

**Comment by kukabi** [comment] 2020-05-28 09:26
Thanks for the report @hansfordj. What version is your app? It looks like a duplicate of https://github.com/tari-project/wallet-android/issues/343, so it might be resolved with one of the more recent versions.

**Comment by Tas4tari** [comment] 2020-06-01 09:49
Tested the push notification redirect on v0.1.14: Tested sucessfully
https://drive.google.com/file/d/1p1KvqF1PKfGDsgUfHrW362uNuNH85l-a/view?usp=sharing

**Closed** 2020-06-01 12:59 UTC
