### ISSUE TITLE
[Feature] Encrypted cloud backup (password)

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#429] opened 2020-06-09 15:16 UTC
See [parent](https://github.com/tari-project/tari/issues/1973)

**Comment by Tas4tari** [comment] 2020-07-03 08:38
@nyarian Enter password screen to go in the Restore flow: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ef40c39f47783a0be5cc238

**Comment by Tas4tari** [comment] 2020-07-03 08:46
@nyarian
Kutsal: i think we have to also input the existing password for a password change

i'm guessing it would just add another text field before the first one, but we need the copy for that one too

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed93db9928c41744f9b07

**Comment by Tas4tari** [comment] 2020-07-03 09:01
@nyarian Question to Tal based on the following video: https://drive.google.com/file/d/1ESslgcc4yqKapcrt8PrWSRBkJINRtqOl/view

**Question:**
You can see that there is, like, no animation for the options show up

it's a little bit more complex here: the fade in animation that shows all the backup options after signing in starts, but right after that the app receives the info that the last backup was successful and intents to hide the "back up now" button, again, with an (fade-out) animation, so it cancels the currently running (fade in) animation to aviod conflicts and starts the fade out, which is kinda unseen because the view didn't even appear in the first place

how do you want this to behave? fading in all the other options and fading out the "back up now" concurrently, silently and quickly hiding the "back up now" button, or something else?

**Response:**"
Fading in all the other options and fading out the "back up now" concurrently" --> would this make it look like what @SerhiiShovkoplias  has on iOS?  I think the fade-in looks pretty nice there.  Or would it be different due to the conflict you mention?

**Andri**
well, backing up is a kinda long process in the video Sergii sent, so the fade in has all the necessary time to complete and fade out starts only after fade in animation is completed

**Comment by Tas4tari** [comment] 2020-07-03 09:01
**Received from Tal:**
As for the last case you guys brought up on standup today (@kutsal I think it was you who explained it?) around add/change pw and the next backup having to be tied together as far as success/failure, what do you think of retrying 3 times and then displaying the relevant error message while keeping user on the select password screen? This way they can resolve whatever the issue is and get back to that screen to try to save again once they return to the app.  If for whatever reason they close the app altogether and reopen it, they'll have to start over again, but it won't be unexpected because they never got the feedback that their password was successfully saved (or had any reason to think it might've been, e.g. if they were sent back to the prior screen)

**Comment by nyarian** [comment] 2020-07-03 10:54
Applied opinionated reasoning to the animation: it just runs sequential now - first it completely fades in, then the "back up now" option is being hidden with fade out if it should. I think it is be the behavior user expects, but if you have another opinion on this, then ping me :)

**Comment by kutsal** [comment] 2020-07-07 12:37
@Tas4tari I don't think I'm the "Kutsal" you need to chime in on this. I think you meant @kukabi based on contributors :)

**Comment by Tas4tari** [comment] 2020-07-15 06:49
@kukabi @nyarian  Please see added requirement and design as discussed in stand up:
**Added Requirement:**
**Password Error message:**

- Error should only appear once first password field is no longer in focus (that is, once user taps out of it, usually in order to enter it again in the pw confirmation field)
- Design: http://zpl.io/VxzWw4X

I have also updated the parent ticket with this
cc @talmahaj

**Comment by Tas4tari** [comment] 2020-07-16 13:11
Testing on Huawei P30 lite, app version: v0.3.0-jnLibs-0.15.2
A few notes on what I have picked up thus far from testing:
cc @kukabi @nyarian 
**Color of the backups enabled button is red as opposed to green which is incorrect. Design reference: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf7fb40e1a33d60c1e2
Title differs from design, is displayed as: "Secure your Google Drive backup" [I think this is fine, just need confirmation from @talmahaj as I cannot remember if it was brought up in discussion] : https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf9fe48f580cf0acc05
Title of Password section states: Enter Password and not Create a Password as per the design referenced here: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf9fe48f580cf0acc05
User on Android does not see the "Backing up your wallet screen" as the design referenced here: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed5f81c864776a3c79cdf**

**Videos:**
**Create Password:** https://drive.google.com/file/d/10wiuqSeO2jgQe-JQl3oP44vQmdiayInM/view?usp=sharing
**Change Password:** https://drive.google.com/file/d/1x2uFpPtHGQ56qVWdCNTbVD769m2-om1n/view?usp=sharing

**Comment by Tas4tari** [comment] 2020-07-17 16:03
Tickets have been created for the following:

- [Backup and Restore: Restore Wallet screen: Encrypted and Unencrypted backup flow](https://github.com/tari-project/wallet-android/issues/474)
- [Backup and Restore: Automatic Backup Toggle button color is not as per design](https://github.com/tari-project/wallet-android/issues/473)

All other UI issues listed have already been addressed by @nyarian

**Comment by Tas4tari** [comment] 2020-07-17 16:27
@nyarian Will the UI fixes from above that you have already completed, be merged in for testing before the release or will it go with the next release

**Comment by Tas4tari** [comment] 2020-07-24 07:03
Tested on Huawei P30 Lite, App version: v0.3.0-jnLibs-0.16.0:
**Retest list:**

- Title differs from design, is displayed as: "Secure your Google Drive backup" : https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf9fe48f580cf0acc05: Tested successfully.
- Title of Password section states: Enter Password and not Create a Password as per the design referenced here: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf9fe48f580cf0acc05: **Tested, displays as Create Password and not Create a Password as per the design**
- User on Android does not see the "Backing up your wallet screen" as per the design referenced here: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed5f81c864776a3c79cdf: **This was discussed in standup that this will not be displayed for Android**
- Change your password button is enabled even before the user has entered anything, should this not be consistent with the "Secure Your Backup" button and be disabled until the user enters a password? **
- "Restore Wallet" button is enabled before the user enters a password, same as the above comment

**Comment by Tas4tari** [comment] 2020-07-24 07:18
Should I break those 2 into separate issues? @nyarian @kukabi

**Comment by Tas4tari** [comment] 2020-07-24 08:29
**Tested unsuccessfully:**

- Title of Password section states: Enter Password and not Create a Password as per the design referenced here: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bf9fe48f580cf0acc05

The text states "Create Password" and not "Create a Password"

**Comment by Tas4tari** [comment] 2020-07-27 13:14
Tested successfully on Huawei P30 Lite, using the Regular release apk, password field has changed to reflect the correct text as per the design:
![photo_2020-07-27 15 13 36](https://user-images.githubusercontent.com/50987039/88545810-c7066180-d01b-11ea-9ab5-40182358faab.jpeg)

**Closed by Tas4tari** 2020-07-27 13:14 UTC

**Comment by Tas4tari** [comment] 2020-07-28 08:51
Tested successfully on the Beta release
![photo_2020-07-28 10 49 59](https://user-images.githubusercontent.com/50987039/88641911-1b631d00-d0c0-11ea-89f3-a10313b737b8.jpeg)
