### ISSUE TITLE
[Feature] Store & Forward UX

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#274] opened 2020-04-14 05:27 UTC
See [parent](https://github.com/tari-project/tari/issues/1694)

**Comment by talmahaj** [comment] 2020-04-14 05:28
@kukabi just FYI this is our top pri now, thx!

**Comment by talmahaj** [comment] 2020-04-16 00:35
@kukabi @Jasonvdb per my mattermost message, see parent ticket for updated specs and copy for  status animation

**Comment by Tas4tari** [comment] 2020-05-04 13:37
@kukabi Testing as an internal user:

**Scenarios:**
1. When i tested with my existing wallet, (App was force closed and re-opened) I found that as it's checking for updates, the app crashes
2. I then uninstalled and re-installed a new wallet via https://play.google.com/apps/internaltest/4701539638446010320 and I found that when I get to the transaction list screen, whilst in "Checking for updates" state the app crashes in the same way once again.
It seems in the above 2 scenarios it loops in a constant state of "Checking for updates"

**Version:**
v0.1.8-jniLibs-0.9.0 

**Device:**
Huawei P30 lite

**Logs:**
[ffi_logs_C6134EE189880B7F8802C6472F09454AFF5D9A1E593E0E0875251451B0584945.zip](https://github.com/tari-project/wallet-android/files/4574938/ffi_logs_C6134EE189880B7F8802C6472F09454AFF5D9A1E593E0E0875251451B0584945.zip)

**Comment by nyarian** [comment] 2020-05-21 12:21
@Tas4tari is this one still reproducible? Couldn't trigger crash a single time. Seems to be quite aged - could be resolved by some overall fixes done to the codebase.

**Comment by kukabi** [comment] 2020-05-21 12:22
@Tas4tari moving back to UAT for now. @nyarian

**Comment by Tas4tari** [comment] 2020-05-25 16:58
@nyarian No longer reproducible

**Comment by Tas4tari** [comment] 2020-05-25 17:25
Tested on Huawei P30 lite:
@nyarian All store and forward animations appear only with the pull to refresh

- If Tor is not connected and/or base node isn't in sync: Sand timer icon and "Checking for updates" : **Tested successfully**
- If user is connected/synced AND has a transaction to accept: Handshake icon and "Receiving new transactions" (should show for minimum 3 seconds): **Tested successfully - user was online and whilst sender transaction was in the sending process, the recipient did a pull to refresh and received the status.**
- If user is connected/synced AND has a transaction to broadcast: Handshake icon and "Completing your transaction" (should show for a minimum 3 seconds): **Tested successfully**
- If user is connected/synced AND has no more outstanding transaction interactions "You are up to date!" (if there is a new transaction accepted, should appear in list at the same time as the above does): **Tested successfully**
- If user is connected/synced AND has a transaction that expired: Handshake icon and "Updating your transaction" (should show for a minimum 3 seconds) **Testing in progress**
- If user pulls down on transaction list to refresh, force a base node sync manually and display sand timer icon and "checking for updates" for at least 2 seconds: **Tested successfully**

**Comment by Tas4tari** [comment] 2020-05-25 17:29
@Tas4tari Check in 3 days at 19:26 for the status animation in point 5

**Comment by Tas4tari** [comment] 2020-05-25 17:50
**App opened:**
![Screenshot_20200525_190357_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834117-70b45f80-9ec0-11ea-93d3-822adc327739.jpg)
![Screenshot_20200525_190411_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834157-93467880-9ec0-11ea-8081-638ebc5f05a7.jpg)


**Receiving and Completing Transactions:**
![Screenshot_20200525_192117_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834197-b1ac7400-9ec0-11ea-8f63-0e1cf75ef3d0.jpg)
![Uploading Screenshot_20200525_192120_com.tari.android.wallet.jpg…]()


**Pull to refresh:**
![Screenshot_20200525_192348_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834274-e28ca900-9ec0-11ea-9e92-df3670af87d6.jpg)

**Closed** 2020-05-26 08:03 UTC
