### ISSUE TITLE
[Feature] Store &amp; Forward - Addl UX improvements

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#298] opened 2020-04-23 07:24 UTC
See [parent](https://github.com/tari-project/tari/issues/1750)

**Comment by Tas4tari** [comment] 2020-04-28 12:03
Tested on Huawei P30 lite:
**Waiting for recipient to accept a transaction**
![Screenshot_20200428_135240_com tari android wallet](https://user-images.githubusercontent.com/50987039/80485076-0d82ec00-8959-11ea-9424-55c0244004e9.jpg)

**Comment by Tas4tari** [comment] 2020-04-28 12:06
Tested on Huawei P30 lite:
**Completing final processing**
![Screenshot_20200428_134534_com tari android wallet](https://user-images.githubusercontent.com/50987039/80485172-34d9b900-8959-11ea-9c83-51c71ac4a79a.jpg)

**Comment by Tas4tari** [comment] 2020-04-30 10:59
To test second status:
Sender should send a transaction, close their device and recipient should open their app and view the transaction that is from sender, status on Transaction details screen should display as:"Waiting for sender to complete transaction"

**Comment by Tas4tari** [comment] 2020-04-30 12:43
@kukabi Tested the second status unsuccessfully. Only status display is "Completing final processing..."

**Comment by Tas4tari** [comment] 2020-04-30 12:59
![WhatsApp Image 2020-04-30 at 14 22 05](https://user-images.githubusercontent.com/50987039/80713033-1a3b4780-8af3-11ea-96da-4547c3f20723.jpeg)

**Comment by Tas4tari** [comment] 2020-04-30 13:31
@nyarian @kukabi  Here are some steps that will help to reproduce:
**Test 1**
**Pre-conditions:**
Android user is not on the app, but the XTR Wallet service is running

**Steps:**

1. Sender opens app and sends a transaction to the user
2. Recipient receives push notification but does not open app
3. Sender force closes app whilst transaction is still "In Progress"
4. Recipient opens the app via Homescreen icon and not push notification and see the transaction In Progress on Transactions list
5. Recipient clicks on In Progress transaction
6. Status is displayed as "Completing final processing"
7. Recipient goes back to Transaction list screen
8. Sender comes back online
9. Status remains as "Completing final processing"
10. 
11. **Test 2:**
12. **Pre-conditions:**
13. Recipient (Android user) is on the Transactions list screen
14. 

1. Sender opens app and sends a transaction to the user
2. Recipient sees Transaction in Progress appear on transaction list
3. Sender force closes app whilst transaction is still "In Progress" on recipient end
4. Recipient clicks on In Progress transaction
5. Status is displayed as "Completing final processing"
6. Recipient goes back to Transaction list screen
7. Sender comes back online
8. Status remains as "Completing final processing"

**Comment by talmahaj** [comment] 2020-05-01 05:04
@Tas4tari when you move tix back to up next, pls be sure to drag them back to the top so we can prioritize the fixes. thx!

**Comment by talmahaj** [comment] 2020-05-01 05:11
@Tas4tari on Android the 2nd status would actually be skipped because the wallet service is always running (unlike on iOS), so unless the sender terminates the service no one would see this step. Does the 2nd status appear IF the service is terminated or if the other user is offline due to no connectivity? Because that should be the only case I can think of... Right @kukabi ?

**Comment by Tas4tari** [comment] 2020-05-01 05:47
@talmahaj  We tested by killing the background service of the Sender's device by closing the app via the App manager.
Will try the "No connectivity" use case and confirm what the behaviour is there

**Comment by kukabi** [comment] 2020-05-01 07:12
@Tas4tari I'm assuming both the sender and receiver are on Android. First 9 steps look as expected, also the next 8-step sequence looks ok to me, @talmahaj can you please confirm? Force-closing an app will not actually turn the wallet off unless the user force-kills the app through Settings, so the communication between wallets will still happen between backgrounded Android devices. "Completing final processing..." means the the transaction is being mined, so if a transaction has reached this state it's a good thing.

**Comment by Tas4tari** [comment] 2020-05-01 07:16
@kukabi Apologies for the confusion, when I say force closes, I meant that we killed the app via Settings  - App Manager - aPP

**Comment by Tas4tari** [comment] 2020-05-15 09:59
@nyarian @kukabi Tested on Huawei P30 lite, App version v0.1.11-jniLibs-0.9.2:
When executing the "Waiting for recipient to accept transaction" I find the following happen.

Once i send through tXTR to a recipient that is not on the app, when I go to the TDS, it shows the "Waiting for recipient to accept transactions" correctly however, whilst waiting on the Transaction Details screen, and the recipient comes online it updates to "Payment Sent" on the sender side,   this is incorrect as when i go back to the Transaction list screen, the transaction is still "In Progress" and when I select to view the TDS for the transaction, I find that it's in the "Completing final processing" state.

**Steps to reproduce:**
**Pre-conditions:**

- Recipient should have the app killed (Background service is not running

Steps:

1. Sender logs into the App and sends a transaction to the recipient that is not on the app
2. Transaction goes through the Discovery process on the app and is successful
3. Sender sees the transaction In Progress
4. Sender clicks on the transaction and is navigated to the TDS
5. Status displayed to the sender on the TDS is "Waiting for recipient to accept transaction" Recipient does not receive a push notification
6. Recipient logs into the app
7. Sender is still on the TDS and sees the TDS update to "Payment sent"
8. When the sender navigates to the Transaction list the transaction is still "In Progress"
9. Sender does a Pull to refresh" and the status is still In Progress
10. When  the sender clicks on the Transaction again it displays as "Completing Final processing"
11. Recipient sees the senders transaction as "In Progress" and when the transaction is selected the status displayed is "Completing final processing"


**Additional Notes:**
When we tried to reproduce the second time, behaviour of Step 10  is inconsistent on the second try it displayed as "Waiting for recipient to accept transaction"

**Logs:**
[ffi_logs_1CE88949683DEC11833D32F6C188C7638720C9022B5DE89EFBADEC1C6F8A436D.zip](https://github.com/tari-project/wallet-android/files/4633657/ffi_logs_1CE88949683DEC11833D32F6C188C7638720C9022B5DE89EFBADEC1C6F8A436D.zip)

**Comment by Tas4tari** [comment] 2020-05-15 10:18
The screenshots:
![Screenshot_20200515_121052_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039733-bd6c8f00-96a5-11ea-9e3f-e12fbf97c8ab.jpg)
![Screenshot_20200515_120918_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039768-c9f0e780-96a5-11ea-8685-bf6e0f7b0222.jpg)
![Screenshot_20200515_120914_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039810-d4ab7c80-96a5-11ea-90b7-cc998cee5529.jpg)
![Screenshot_20200515_121100_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039856-e42ac580-96a5-11ea-9321-48b303020d84.jpg)
![Screenshot_20200515_121102_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039905-f60c6880-96a5-11ea-9890-e5e46b0c70c1.jpg)
![Screenshot_20200515_121111_com tari android wallet](https://user-images.githubusercontent.com/50987039/82039989-1b00db80-96a6-11ea-89f4-04cd5c2c1079.jpg)

**Comment by Tas4tari** [comment] 2020-05-15 10:23
![1](https://user-images.githubusercontent.com/50987039/82040379-cd38a300-96a6-11ea-9659-87e4c2ebb917.jpg)
![2](https://user-images.githubusercontent.com/50987039/82040391-d1fd5700-96a6-11ea-89a0-e7b0d66f56e9.jpg)
![3](https://user-images.githubusercontent.com/50987039/82040394-d32e8400-96a6-11ea-850b-63448026c680.jpg)
![4](https://user-images.githubusercontent.com/50987039/82040401-d4f84780-96a6-11ea-828b-c334b59abb95.jpg)
![5](https://user-images.githubusercontent.com/50987039/82040407-d6c20b00-96a6-11ea-92c4-5542c65d21e1.jpg)
![6](https://user-images.githubusercontent.com/50987039/82040415-d9246500-96a6-11ea-9e95-8c0079b2daa3.jpg)
![7](https://user-images.githubusercontent.com/50987039/82040423-daee2880-96a6-11ea-8e41-343f0b8856e3.jpg)

**Comment by Tas4tari** [comment] 2020-05-26 08:01
Tested in Huawei P30 lite:

- Remove animation on top right of In Progress section on transactions list screen. It makes sense for transactions that are only in progress for a few minutes due to being mined, but not for ones that are being stored and forwarded. **Tested successfully**
- Transaction detail page should show similar element to status bar:

Statuses:
- Depending on status, copy should read:
- "Waiting for recipient to accept transaction" (not accepted): **Tested successfully**
Test proof: https://www.loom.com/share/294380435d4d46a4afcab43e1fd67648
- "Waiting for sender to complete transaction" (accepted, not broadcasted): Still testing
- "Completing final processing…" (broadcast) **Tested successfully**
Test proof: https://www.loom.com/share/294380435d4d46a4afcab43e1fd67648

**Comment by Tas4tari** [comment] 2020-05-27 12:24
**Waiting for sender to complete transaction**
Tested successfully on Huawei on P30 lite
![image-22ffd33a-c3d1-4255-9c98-0b5131b6cc7d](https://user-images.githubusercontent.com/50987039/83018448-9dce5280-a025-11ea-864f-1e45b1644af7.jpg)
![image-448dfdc8-8190-4460-821b-b5282224aeb4](https://user-images.githubusercontent.com/50987039/83018463-a7f05100-a025-11ea-9941-30ce88123593.jpg)

**Closed** 2020-05-27 12:24 UTC
