### ISSUE TITLE
[QA tested] Users doesn't receive notifications

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1123] opened 2024-06-05 14:11 UTC
Users doesn't receive any notifications from Aurora when they have their notifications enabled.

This is on a Xiaomi Redmi Note 10S on Android 13

This is on the bitrise (293) version

**Comment by igordanilcenko** [comment] 2024-08-20 11:49
Notifications look empty, should be fixed 

<img src="https://github.com/user-attachments/assets/83cb54f0-e74c-44af-a8e8-817f52edb2b0" width="350" />

**Closed** 2024-09-04 14:42 UTC
Labels: Bug - Minor

**Comment by igordanilcenko** [comment] 2024-09-05 15:37
The task about missing layout is added to the `Non-critical bugs`. Closing because it's confirmed that notifications works
