### ISSUE TITLE
Issue with Android app

### ISSUE THREAD

**Issue by michael60634** [tari-project/wallet-android#615] opened 2021-04-18 00:42 UTC
Tari on Android crashes immediately when launched. My Android device is a Google Pixel 4 with Android 11.

**Comment by kukabi** [comment] 2021-04-19 09:14
Thanks for the report @michael60634. I failed to find the report for your case in our crash reporting tool. We're preparing a new release and I'm not able to reproduce the bug on Android 11 - so it might be fixed with this version. But just to make sure and get more details, were you able to create your wallet, i.e. does the app crash when you're trying to open the home screen? Or does it crash immediately after install?

**Comment by kukabi** [comment] 2021-04-19 12:46
@michael60634 you can also try the most recent beta release at https://github.com/tari-project/wallet-android/releases/tag/v0.6.2-b157-libwallet-0.16.27-BETA. You can find the APK files in the release page. Please prefer `Tari-Aurora-0.6.2-b157-libwallet-0.16.27-Regular.apk` for the Play Store version.

**Comment by michael60634** [comment] 2021-04-19 16:02
I was not able to create a new wallet and the app crashes immediately after install.

**Comment by kukabi** [comment] 2021-04-21 06:10
This issue is fixed by the `0.6.2` version available on Play Store and the [GitHub release page](https://github.com/tari-project/wallet-android/releases/tag/v0.6.2-b159-libwallet-0.16.27). Please let us know if the problem persists @michael60634.

**Closed by kukabi** 2021-04-21 06:10 UTC
