### ISSUE TITLE
QA: Clicking on a transaction causes the App to crash

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#233] opened 2020-03-27 11:24 UTC
When hitting the transaction: 987, the App crashes.: Samsung A71 - Android 10
This also happens when selecting a Pending transaction on a Samsung S8
Screenshots for point 1 and 2 below respectively:
![image-7408ed3b-5247-4270-a548-b158495e695c](https://user-images.githubusercontent.com/50987039/77751323-2a609280-702e-11ea-84e4-ee4c285f725a.jpg)
![Screenshot_20200326-180200_Google Play services](https://user-images.githubusercontent.com/50987039/77751642-bf638b80-702e-11ea-9dba-6fb3bd4ae304.jpg)

**Comment by kukabi** [comment] 2020-03-27 13:02
Duplicate of #226, is fixed by PR #225.

**Closed** 2020-03-27 13:24 UTC
Labels: bug
