### ISSUE TITLE
Wrap JNI bindings into class library

### ISSUE THREAD

**Issue by StriderDM** [tari-project/wallet-android#50] opened 2019-11-11 07:03 UTC

**Comment by CjS77** [comment] 2019-11-22 05:53
@StriderDM Duplicate of #46 ?

**Comment by kukabi** [comment] 2020-03-31 09:15
@CjS77 Can we close this one?

**Comment by CjS77** [comment] 2020-04-06 08:51
Yes. Yes, we can.

**Closed by CjS77** 2020-04-06 08:51 UTC
