### ISSUE TITLE
Clicking the "Done" button after editing contact opens the keyboard rather than closes

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/wallet-android#1167] opened 2024-08-30 18:25 UTC
Description:
On my Pixel 7a, Android version 14
1.  User goes to contacts and taps a contact to edit
2. User then taps "Edit"
3. User taps the contact textbox to edit and the keyboard opens to allow editing
4. If the user closes the keyboard manually and taps "Done" the keyboard opens again. 
5. If the User taps "Done" to finish editing, the keyboard stays open - it is not dismissed. The user must manually dismiss the keyboard. 
6. It seems by tapping "Done" it open the keyboard rather than closes it

Can't attach a recording because the phone can't record the taps. 

Aurora: 0.26.1-libwallet-v1.3.0-pre.0

**Comment by igordanilcenko** [comment] 2024-09-05 13:12
Can't replicate on 2 devices. Video from my testing:

https://drive.google.com/file/d/1gjsU86TjqCS9c7mxQYbxO7ZyU3QXD4P5/view?usp=sharing

**Comment by igordanilcenko** [comment] 2024-09-05 15:29
Agreed with @Cultmojo to close it because the issue isn't reproducible anymore

**Closed by igordanilcenko** 2024-09-05 15:29 UTC
Labels: Bug - Major
